registrationUrl=https://app.getcalley.com/registration.aspx

loginUrl=https://app.getcalley.com/Login.aspx

##################################################

name=Test User

email=testuser2011@gmail.com

phone=9922445566

password=Test@123

###############################################

loginEmail= test2026_01@gmail.com

loginPassword=Test@1234

#######################################

agentName=mnm_Agent

agentMobile=9876543210

agentEmail=mnm_Agent@gmail.com

agentPassword=Agent@123

###########################################

listName=TestList2020

csvPath=D:/QA/Projects/Automation/CSTech/Sample File.xlsx