registrationUrl=https://app.getcalley.com/registration.aspx

loginUrl=https://app.getcalley.com/Login.aspx

##################################################

name=Test User

email=testuser_1277@gmail.com

phone=9944557788

password=Test@123

###############################################

loginEmail= testuser2026_07@gmail.com

loginPassword=Test@1234

#######################################

agentName=pkp_Agent

agentMobile=9876543210

agentEmail=pkp_Agent@gmail.com

agentPassword=Agent@123

###########################################

listName=TestList2021

csvPath=D:/QA/Projects/Automation/CSTech/Sample File.xlsx